// Frontend/React/src/views/Home/index.js
import { useState, useEffect } from "react";
import { ChevronRight, Download } from "react-feather";
import { useLocation } from "react-router-dom";

import { getCategories } from "services";
import "./styles.css";

const useQuery = () => {
  return new URLSearchParams(useLocation().search);
};

const getAsArray = (data, isBaseCategory) => {
  if (isBaseCategory) {
    const arr = [];

    for (const index of Object.keys(data.children)) {
      arr.push(data.children[index]);
    }

    data.children = [...arr];
    return data;
  }

  const arr = [];

  for (const index of Object.keys(data)) {
    arr.push(data[index]);
  }

  data = [...arr];
  return data;
};

const Home = () => {
  const [items, setItems] = useState();
  console.log(items);

  let query = useQuery();

  const queryParams = query.get("path");

  const idChild = queryParams && queryParams.split("/");

  let category = "";

  const getAllCategories = async () => {
    try {
      const data = await getCategories();
      setItems(getAsArray(data));
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    if (idChild?.length) {
      for (const child in idChild) {
        if (child === "0") {
          continue;
        }

        if (child === "1") {
          category = items.find(item => item.id === idChild[child]);

          // console.log("category", category);
          // console.log("browsePath", {
          //   url: `${category.browsePath}/${category.id}`,
          // });
          // console.log("label", category.label);

          continue;
        }

        category = getAsArray(category.children).find(
          item => item.id === idChild[child]
        );
      }
      setItems(getAsArray(category.children));
    } else {
      getAllCategories();
    }
  }, []);

  const filterList = event => {
    var updatedList = getAsArray(getCategories());

    updatedList = updatedList.filter(function (item) {
      return (
        item.label.toLowerCase().search(event.target.value.toLowerCase()) !==
          -1 ||
        item.productType
          .toLowerCase()
          .search(event.target.value.toLowerCase()) !== -1 ||
        item.id.search(event.target.value.toLowerCase()) !== -1
      );
    });

    setItems(updatedList);
  };
  const getBread = cat => {
    const browsePathSplited = cat.browsePath.split("/");
    const displayPathSplited = cat.displayPath.split("/");

    const bc = [];

    for (const i in browsePathSplited) {
      let index = Number(i);

      if (index > 0) {
        bc.push({
          id: browsePathSplited[index],
          label: displayPathSplited[index],
          fullPath: `${cat.browsePath
            .split("/")
            .slice(0, index + 1)
            .join("/")}/${browsePathSplited[index + 1]}`,
          isDisabled: browsePathSplited.length === index + 2,
        });
      } else {
        bc.push({
          id: `${browsePathSplited[index]}/${browsePathSplited[index + 1]}`,
          label: displayPathSplited[index],
          fullPath: `${browsePathSplited[index]}/${
            browsePathSplited[index + 1]
          }`,
          isDisabled: browsePathSplited.length === index + 2,
        });
      }
    }

    return bc.slice(0, -1);
  };

  return (
    <main>
      <header className="top-nav">
        <figure>
          <img src="aws-branco.png" alt="Categorias amazon" />
          Amazon - Listagem de Categorias
        </figure>
        <input type="text" placeholder="Categoria" onChange={filterList} />
      </header>

      <div className="container">
        <div className="filter-list">
          {/* <nav aria-label="You are here:" role="navigation">
            <ul className="breadcrumbs">
              <li>
                <a href="/">Categorias</a>
              </li>
              {getBread(getAsArray(items)[0]).map(bread => (
                <li
                  key={bread.id}
                  className={bread.isDisabled ? "disabled" : ""}
                >
                  {bread.isDisabled ? (
                    bread.label
                  ) : (
                    <a href={`http://localhost:3000/?path=${bread.fullPath}`}>
                      {bread.label}
                    </a>
                  )}
                </li>
              ))}
            </ul>
          </nav> */}
          <ul>
            {items &&
              getAsArray(items).map(item => {
                return (
                  <li key={item.id} className="list-items">
                    {item.isSellable ? (
                      <div className="next-category">
                        <section>
                          <div className="parent-title">{item.name}</div>
                          <small>BrowseNodeId: {item.id}</small>
                        </section>
                      </div>
                    ) : (
                      <a
                        href={`?path=${item.browsePath}/${item.id}`}
                        className="next-category"
                      >
                        <section>
                          <div className="parent-title">{item.name}</div>
                          <small>BrowseNodeId: {item.id}</small>
                        </section>
                      </a>
                    )}
                    {!item.isSellable ? (
                      <ChevronRight stroke="#f08804" />
                    ) : (
                      <a
                        href={item?.url}
                        target="_blank"
                        rel="noreferrer"
                        download
                      >
                        <Download />
                      </a>
                    )}
                  </li>
                );
              })}
          </ul>
        </div>
      </div>
    </main>
  );
};

export default Home;

// Frontend/Vuejs/src/views/Home.vue
<template>
    <main>
        <header class="top-nav">
            <figure
                @click="
                    $router.push('/');
                    request([], true);
                "
                style="cursor: pointer"
            >
                <img
                    :src="require('@/assets/aws-branco.png')"
                    alt="Categorias amazon"
                />Amazon - Listagem de Categorias
            </figure>

            <input
                v-model="searchInputValue"
                id="search"
                type="text"
                placeholder="Pesquisar"
                @focus="searchInputIsFocused = true"
                @blur="searchInputIsFocused = false"
                @keyup="search($event)"
            />

            <div class="text-center mt font-sm" style="height: 24px">
                <template v-if="searchInputIsFocused"
                    >Pressione ENTER para pesquisar</template
                >
            </div>
        </header>

        <div class="container">
            <div class="breadcrumb">
                <div v-for="(breadcrumb, index) in breadcrumb" :key="index">
                    <template v-if="!breadcrumb.isFirstIndex">
                        <a :href="`/?pathById=${breadcrumb.path}`">{{
                            breadcrumb.name
                        }}</a>
                    </template>

                    <template v-else>
                        <a href="/">{{ breadcrumb.name }}</a>
                    </template>
                    <span style="margin: 0 10px">/</span>
                </div>
            </div>

            <ul>
                <li
                    class="list-items"
                    v-for="(category, index) in categories"
                    :key="index"
                    @click="
                        redirectTo(
                            category.pathById,
                            category.pathByName,
                            category.documents,
                            Boolean(category.children.length)
                        )
                    "
                >
                    <div>
                        <h5 class="category-name">{{ category.name }}</h5>
                        <small class="category-info">
                            <strong>Browse Node ID:</strong>
                            {{ category.id }}
                        </small>

                        <template v-if="category.productType">
                            <br />
                            <small class="category-info">
                                <strong>Product Type:</strong>
                                {{ category.productType }}
                            </small>
                        </template>

                        <p class="category-info">
                            <strong>Path By Name:</strong>
                            {{ category.pathByName.replace(/,/g, " / ") }}
                        </p>
                    </div>

                    <div>
                        <ChevronRightIcon
                            class="icon text-warning"
                            v-if="category.children.length"
                        />

                        <DownloadIcon class="icon" v-else />
                    </div>
                </li>
            </ul>
        </div>
    </main>
</template>

<script>
import axios from "axios";
import ChevronRightIcon from "vue-material-design-icons/ChevronRight.vue";
import DownloadIcon from "vue-material-design-icons/Download.vue";

export default {
    name: "Home",

    components: {
        ChevronRightIcon,
        DownloadIcon,
    },

    data: () => ({
        searchInputValue: "",
        searchInputIsFocused: false,
        categories: [],
        breadcrumb: [],
        requestedCategoryPathByName: "",
    }),

    async mounted() {
        const pathById = this.$route.query.pathById;

        if (pathById) {
            await this.request([], true);
            this.updateBreadcrumb(pathById, this.requestedCategoryPathByName);
            return;
        }

        const { data } = await axios.get("http://localhost:3333/categories");
        console.log("data (first request)", data);

        this.categories = data;
    },

    methods: {
        async request(documents, currentCategoryHasChildren) {
            if (!currentCategoryHasChildren) {
                window.open(documents[0]);
                return;
            }

            const pathById = this.$route.query.pathById;
            const { data } = await axios.get(
                `http://localhost:3333/categories/search-by-path/${pathById}`
            );

            const oldCategoriesLength = this.categories.length;

            this.categories = data[0].children;
            console.log("data", this.categories);

            this.requestedCategoryPathByName = data[0].pathByName;

            if (!oldCategoriesLength) {
                return;
            }

            // this.updateBreadcrumb(data[0]);
        },
        redirectTo(pathById, pathByName, documents = [], hasChildren) {
            //this.$route.query.pathById
            const lastPathById = this.$route.query.pathById || pathById;
            this.$router.push(`?pathById=${pathById}&last=${lastPathById}`);
            this.request(documents, hasChildren);
            this.updateBreadcrumb(pathById, pathByName);
        },
        async search(event) {
            if (event.code !== "Enter") {
                return;
            }

            event.preventDefault();

            const { data } = await axios.get(
                `http://localhost:3333/categories/search/${this.searchInputValue}`
            );

            this.updateBreadcrumb("", "");

            if (!data.length) {
                alert("Nenhum resultado encontrado");
                return;
            }

            this.categories = data;
        },
        updateBreadcrumb(pathById, pathByName) {
            let mountedPath = "";
            pathByName = pathByName.replace(/, /g, "/");
            pathById = pathById.split(",");
            pathByName = pathByName.split(",");

            const basePathId = pathById[0];
            pathById.splice(0, 1);

            this.breadcrumb = [];

            for (const index in pathById) {
                const isFirstIndex = index === "0";

                mountedPath += isFirstIndex
                    ? `${basePathId},${pathById[index]}`
                    : `,${pathById[index]}`;

                this.breadcrumb.push({
                    path: mountedPath,
                    name: pathByName[index].replace(/\//g, ", "),
                    isFirstIndex,
                });
            }
        },
    },
};
</script>
